Components/CartSummaryViewComponent.cs
using com.cake_lovers.www.Models;
using Microsoft.AspNetCore.Mvc;
namespace com.cake_lovers.www.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Controllers/AdminController.cs
using com.cake_lovers.www.Models;
using com.cake_lovers.www.Models.ModelView;
using com.cake_lovers.www.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Globalization;

namespace com.cake_lovers.www.Controllers
{
    public class AdminController : Controller
    {
        private readonly ILogger<AdminController> _logger;
        private readonly AdminServices _adminService;
        private readonly ProdutoService _produtoService;


        public AdminController(ILogger<AdminController> logger, AdminServices contatoService = null, ProdutoService produtoService = null)
        {
            _logger = logger;
            _adminService = contatoService;
            _produtoService = produtoService;
        }



        [HttpGet]
        public IActionResult GetAllPedidos()
        {
            var pedidos = _adminService.GetAllPedidos().ToList();
            var model = new PedidoModel()
            {
                Pedidos = pedidos,
            };
            return View(model);
        }
        [HttpGet]
        public IActionResult VisualizaPedido(int id)
        {
            var pedido = _adminService.GetPedidoPorId(id);
            return View(pedido);
        }
        [HttpGet]
        public IActionResult DeletaPedido(int id)
        {
            try
            {
                var pedido = _adminService.GetPedidoPorId(id);
                return View(pedido);
            }
            catch (Exception e)
            {
                throw new ArgumentException($"Error = {e.Message}");
            }
        }
        [HttpPost]
        public IActionResult DeletarPedido(int PedidoId)
        {
            try
            {
                if (PedidoId > 0)
                {
                    _adminService.DeletarPedidoPorId(PedidoId);
                    return RedirectToAction(nameof(GetAllPedidos));
                }
                throw new ArgumentException($"Error = não tem id para deleção");
            }
            catch (Exception e)
            {
                throw new ArgumentException($"Error = {e.Message}");
            }
        }
        [HttpGet]
        public IActionResult UpdatePedido(int id)
        {
            var pedido = _adminService.GetPedidoPorId(id);
            return View(pedido);
        }
        [HttpPost]
        public IActionResult UpdatePedido(Pedido pedido)
        {
            _adminService.UpdatePedido(pedido);
            return RedirectToAction(nameof(GetAllPedidos));
        }



        [HttpGet]
        public IActionResult GetAllContatos()
        {
            var list = _adminService.GetAllContatos().ToList();
            var model = new ContatoModel()
            {
                Contatos = list
            };
            return View(model);
        }
        [HttpGet]
        public IActionResult DeletaContato(int id)
        {
            try
            {
                var model = _adminService.GetContatoPorId(id);
                return View(model);
            }
            catch (Exception e)
            {
                throw new ArgumentException($"Error = {e.Message}");
            }
        }
        [HttpPost]
        public IActionResult DeletarContato(int? ContatoId)
        {
            try
            {
                if (ContatoId.HasValue)
                {
                    _adminService.DeletarContatoPorId(ContatoId);
                    return RedirectToAction(nameof(GetAllContatos));
                }
                throw new ArgumentException($"Error = não tem id para deleção");
            }
            catch (Exception e)
            {
                throw new ArgumentException($"Error = {e.Message}");
            }
        }


        [HttpGet]
        public IActionResult GetAllProdutos()
        {
            var list = _adminService.GetAllProdutos().ToList();
            var model = new ProdutoModel()
            {
            Produtos = list
            };
            return View(model);

        }
        [HttpPost]
        public async Task<IActionResult> AdicionaProduto(ProdutoModel model)
        {
            try
            {
                if (model.NovoProduto.Id > 0)
                {
                    _adminService.UpdateProduto(model.NovoProduto);
                    return RedirectToAction(nameof(GetAllProdutos));
                }
                ModelState.Remove("Id");
                ModelState.Remove("NovoProduto.ImagePath");
                if (!ModelState.IsValid)
                {
                    return RedirectToAction(nameof(GetAllProdutos));
                }
                if (model.ProdutoImagem != null)
                {
                    var uploadsFolder = Path.Combine("wwwroot", "images");
                    var uniqueFileName = $"{Guid.NewGuid()}_{model.ProdutoImagem.FileName}";
                    var filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await model.ProdutoImagem.CopyToAsync(fileStream);
                    }

                    model.NovoProduto.ImagePath = $"/images/{uniqueFileName}";
                    await _produtoService.AddProduto(model.NovoProduto);
                }
                return RedirectToAction(nameof(GetAllProdutos));
            }
            catch (Exception e)
            {
                throw new ArgumentException($"Erro durante a ação de adicionar produtos = {e.Message}");
            }
        }
        [HttpGet]
        public IActionResult UpdateProduto(int id)
        {
            var produto = _adminService.GetProdutosPorId(id);
            return View(produto);
        }
        [HttpPost]
        public IActionResult UpdateProduto(Produto produto)
        {
            produto.Preco = Convert.ToDecimal(Request.Form["Preco"].ToString().Replace(".", "").Replace(",", "."));
            _adminService.UpdateProduto(produto);
            return RedirectToAction(nameof(GetAllProdutos));
        }
        [HttpGet]
        public IActionResult DeletaProduto(int? id)
        {
            try
            {
                if (id.HasValue)
                {
                    var produto = _produtoService.GetAllProdutosForId(id);
                    return View(produto);
                }
                throw new ArgumentException($"Error = erro ao solicitar o produto para deletar");
            }
            catch (Exception e)
            {
                throw new ArgumentException($"Error = {e.Message}");
            }
        }
        [HttpPost]
        public IActionResult DeletarProduto(int? Id)
        {
            try
            {
                if (Id.HasValue)
                {
                    _produtoService.DeletarProdutoPorId(Id);
                    return RedirectToAction(nameof(GetAllProdutos));
                }
                throw new ArgumentException($"Error = não tem id para deleção");
            }
            catch (Exception e)
            {
                throw new ArgumentException($"Error = {e.Message}");
            }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProdutoController.cs
using com.cake_lovers.www.Data;
using com.cake_lovers.www.Models;
using com.cake_lovers.www.Models.ModelView;
using com.cake_lovers.www.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Globalization;

namespace com.cake_lovers.www.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly ILogger<ProdutoController> _logger;
        private readonly CakeLoversDbContext _context;
        private readonly ProdutoService _produtoService;
        private readonly Cart cart;


        public ProdutoController(ILogger<ProdutoController> logger, CakeLoversDbContext produtoService, Cart cart, ProdutoService produto)
        {
            _produtoService = produto;
            _logger = logger;
            _context = produtoService;
            this.cart = cart;
        }
        [HttpGet]
        public IActionResult Index(string? termo)
        {
            try
            {
                var produtos = _produtoService.GetAllProdutos();
                var view = new ProdutoModel { Produtos = produtos, NovoProduto = new Produto() };
                return View(view);
            }
            catch (Exception e)
            {
                throw new ArgumentException($"Erro = {e.Message} + \n Trace = {e.StackTrace}");
            }
        }

        [HttpGet]
        public ViewResult EscolherProdutos(string? category, int productPage = 1)
        => View(new CarrinhoModel
        {
            Produtos = _context.Produtos
                    .Where(p => category == null || p.Categoria == category)
                   .OrderBy(p => p.Id),

            PagingInfo = new PagingInfo
            {
                CurrentPage = productPage,
                TotalItems = category == null
                ? _context.Produtos.Count()
                        : _context.Produtos.Where(e =>
                            e.Categoria == category).Count()
            },
            CurrentCategory = category
        });

        [HttpGet]
        public ViewResult Checkout() => View(new Pedido());

        [HttpPost]
        public IActionResult AdicionaMensagemContato(Contato contato)
        {
            try
            {
                var resultado = _context.Contatos.Add(contato);
                _context.SaveChanges();
                return RedirectToPage("/Agradecimento");
            }
            catch (Exception e)
            {
                throw new ArgumentException($"Erro ao adicionar contato. -> {e.Message} \n ->{e.StackTrace}");
            }

        }

        [HttpPost]
        public IActionResult Checkout(Pedido order)
        {

            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Desculpe, O carrinho está vazio!");
            }
            if (ModelState.IsValid)
            {
                order.LinhaDeProdutos = cart.Lines.ToArray();
                _produtoService.SalvarPedido(order);
                cart.Clear();
                return RedirectToPage("/ConclusaoPedido", new { PedidoId = order.PedidoId });
            }
            else
            {
                return View();
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/ProductSummary.cshtml
@using com.cake_lovers.www.Intrastructure;

@model Produto
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model?.NomeProduto
            <span class="badge rounded-pill bg-primary text-white"
                  style="float:right">
                <small>@Model?.Preco.ToString("c")</small>
            </span>
        </h4>
    </div>
    <form id="@Model?.Id" asp-page="/Cart" method="post">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model?.Descricao
            <button type="submit"
                    class="btn btn-success btn-sm pull-right" style="float:right">
                Adicionar ao Carrinho
            </button>
        </span>
    </form>
</div>

Views/Shared/_Layout.cshtml
@using com.cake_lovers.www.Intrastructure;
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cake-lovers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/com.cake_lovers.www.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3 text-white">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">
                    <img src="~/images/logo2.jpg" alt="Logo da Loja" style="height: 35px;">
                    <span>Cake-lovers</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Produto" asp-action="EscolherProdutos">CupCakes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Contato">Contato</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="SobreNos">Sobre Nós</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Política de Privacidade</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Gestão
                            </a>
                            <ul class="dropdown-menu bg-dark text-white " aria-labelledby="navbarDropdown">
                                <li><a class="nav-link " asp-area="" asp-controller="Admin" asp-action="GetAllProdutos">Produtos</a></li>
                                <li><a class="nav-link " asp-area="" asp-controller="Admin" asp-action="GetAllPedidos">Pedidos</a></li>
                                <li><a class="nav-link " asp-area="" asp-controller="Admin" asp-action="GetAllContatos">Contatos</a></li>


                            </ul>
                        </li>
                    </ul>
                </div>
                <div id="categories" class="justify-content-end mx-4">
                    @*<vc:cart-summary />*@
                    <a asp-page="/Cart" asp-route-Id="0" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()" class="cart-icon">
                        <i class="fas fa-shopping-cart text-white">
                        </i>
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div id="categories" class="pb-3">
            <vc:Navigation-Menu />            
        </div>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted fixed-bottom">
        <div class="container">
            &copy; 2024 - Cake-Lovers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Política de Privacidade</a>
        </div>
    </footer>

    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/encontracep.js" asp-append-version="true"></script>
    <script src="~/js/all.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/js/all.min.js" integrity="sha512-6sSYJqDreZRZGkJ3b+YfdhB3MzmuP9R7X1QZ6g5aIXhRvR1Y/N/P47jmnkENm7YL3oqsmI6AK+V6AD99uWDnIw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mask-plugin/1.14.16/jquery.mask.min.js"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>