Models/Cart.cs
namespace com.cake_lovers.www.Models
{
    public class Cart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();
        public virtual void AddItem(Produto produto, int quantidade)
        {
            CartLine? line = Lines
            .Where(p => p.Produto.Id == produto.Id)
            .FirstOrDefault();
            if (line == null)
            {
                Lines.Add(new CartLine
                {
                    Produto = produto,
                    Quantidade = quantidade
                });
            }
            else
            {
                line.Quantidade += quantidade;
            }
        }
        public virtual void RemoveLine(Produto produto) => Lines.RemoveAll(l => l.Produto.Id == produto.Id);
        public decimal ComputeTotalValue() => Lines.Sum(e => e.Produto.Preco * e.Quantidade);
        public virtual void Clear() => Lines.Clear();
    }
    public class CartLine
    {
        public int CartLineID { get; set; }
        public virtual Produto Produto { get; set; } = new();
        public int Quantidade { get; set; }
    }
}

Controllers/ProdutoController.cs
using com.cake_lovers.www.Data;
using com.cake_lovers.www.Models;
using com.cake_lovers.www.Models.ModelView;
using com.cake_lovers.www.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Globalization;

namespace com.cake_lovers.www.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly ILogger<ProdutoController> _logger;
        private readonly CakeLoversDbContext _context;
        private readonly ProdutoService _produtoService;
        private readonly Cart cart;


        public ProdutoController(ILogger<ProdutoController> logger, CakeLoversDbContext produtoService, Cart cart, ProdutoService produto)
        {
            _produtoService = produto;
            _logger = logger;
            _context = produtoService;
            this.cart = cart;
        }
        [HttpGet]
        public IActionResult Index(string? termo)
        {
            try
            {
                var produtos = _produtoService.GetAllProdutos();
                var view = new ProdutoModel { Produtos = produtos, NovoProduto = new Produto() };
                return View(view);
            }
            catch (Exception e)
            {
                throw new ArgumentException($"Erro = {e.Message} + \n Trace = {e.StackTrace}");
            }
        }

        [HttpGet]
        public ViewResult EscolherProdutos(string? category, int productPage = 1)
        => View(new CarrinhoModel
        {
            Produtos = _context.Produtos
                    .Where(p => category == null || p.Categoria == category)
                   .OrderBy(p => p.Id),

            PagingInfo = new PagingInfo
            {
                CurrentPage = productPage,
                TotalItems = category == null
                ? _context.Produtos.Count()
                        : _context.Produtos.Where(e =>
                            e.Categoria == category).Count()
            },
            CurrentCategory = category
        });

        [HttpGet]
        public ViewResult Checkout() => View(new Pedido());

        [HttpPost]
        public IActionResult AdicionaMensagemContato(Contato contato)
        {
            try
            {
                var resultado = _context.Contatos.Add(contato);
                _context.SaveChanges();
                return RedirectToPage("/Agradecimento");
            }
            catch (Exception e)
            {
                throw new ArgumentException($"Erro ao adicionar contato. -> {e.Message} \n ->{e.StackTrace}");
            }

        }

        [HttpPost]
        public IActionResult Checkout(Pedido order)
        {

            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Desculpe, O carrinho está vazio!");
            }
            if (ModelState.IsValid)
            {
                order.LinhaDeProdutos = cart.Lines.ToArray();
                _produtoService.SalvarPedido(order);
                cart.Clear();
                return RedirectToPage("/ConclusaoPedido", new { PedidoId = order.PedidoId });
            }
            else
            {
                return View();
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pages/Cart.cshtml.cs
using com.cake_lovers.www.Infrastructure;
using com.cake_lovers.www.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using com.cake_lovers.www.Data;

namespace com.cake_lovers.www.Pages
{
    public class CartModel : PageModel
    {
        private CakeLoversDbContext repository;
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; } = "/";
        public CartModel(CakeLoversDbContext repo, Cart cartService)
        {
            repository = repo;
            Cart = cartService;
        }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }
        //public IActionResult OnPost(long Id, string returnUrl)
        //{
        //    var product = repository.Produtos
        //    .FirstOrDefault(p => p.Id == Id);
        //    if (product != null)
        //    {
        //        Cart.AddItem(product,1);
        //    }
        //    return RedirectToPage(new { returnUrl = returnUrl });
        //}
        public IActionResult OnPost(long Id, string returnUrl)
        {
            var product = repository.Produtos.FirstOrDefault(p => p.Id == Id);
            if (product != null)
            {
                Cart.AddItem(product, 1);
            }
            return RedirectToPage(new { returnUrl = returnUrl });
        }
        public IActionResult OnPostRemove(long Id, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl =>
            cl.Produto.Id == Id).Produto);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
        //    public IActionResult OnPost(long Id, string returnUrl)
        //    {
        //        if(  Id == 0)
        //        {
        //            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        //            HttpContext.Session.SetJson("cart", Cart);
        //            return RedirectToPage(new { returnUrl = returnUrl });

        //        }
        //        var produto = repository.Produtos.FirstOrDefault(p => p.Id == Id);
        //        if (produto != null)
        //        {
        //            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        //            Cart.AddItem(produto, 1);
        //            HttpContext.Session.SetJson("cart", Cart);
        //        }
        //        return RedirectToPage(new { returnUrl = returnUrl });
        //    }
        //}
    }
}

Pages/Agradecimento.cshtml
@page


<div class="text-center">
    <div class="figure-container">
        <img src="~/images/logo2.jpg" class="img-fluid image-opacity" alt="Logo da Loja" style="height: 120px;">
    </div>
    <h2 class="display-5">Cake-Lovers</h2>
</div>

<div class="text-center mt-5">
    <h1 class="mb-5">Obrigado pelo contato!</h1>
    <h3 class="mb-2">O Responderemos a sua mensagem o mais breve possível nos canais de informação que enviou.</h3>
    <a class="btn btn-primary" asp-controller="Home">Retornar às Compras</a>
</div>

}

Pages/Cart.cshtml
@page
@using com.cake_lovers.www.Models;
@model com.cake_lovers.www.Pages.CartModel
@{
}

<div class="figure-container text-center">
    <img src="~/images/logo2.jpg" class="img-fluid image-opacity" alt="Logo da Loja" style="height: 120px;">
    <h2 class="display-5">Cake-Lovers</h2>

</div>

<div class="container mt-5">
    <h2 class="mb-4">Carrinho de Compras</h2>
    <div class="table-responsive">
        <table class="table align-middle">
            <thead class="table-light">
                <tr>
                    <th scope="col">Produto</th>
                    <th scope="col">Preço</th>
                    <th scope="col">Quantidade</th>
                    <th scope="col">Subtotal</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var line in Model?.Cart?.Lines ?? Enumerable.Empty<CartLine>())
                {
                    <tr>
                        <td class="text-left">@line.Produto.NomeProduto</td>
                        <td class="text-right">@line.Produto.Preco.ToString("c")</td>
                        <td class="text-center">@line.Quantidade</td>
                        <td class="text-right">
                            @((line.Quantidade * line.Produto.Preco).ToString("c"))
                        </td>
                        <td class="text-center">
                            <form asp-page-handler="Remove" method="post">
                                <input type="hidden" name="Id"
                                   value="@line.Produto.Id" />
                                <input type="hidden" name="returnUrl"
                                   value="@Model?.ReturnUrl" />
                                <button type="submit" class="btn btn-sm btn-danger">
                                    Remover
                                </button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-right">Total:</td>
                    <td class="text-right">
                        @Model?.Cart?.ComputeTotalValue().ToString("c")
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>

    <!-- Total e Botões -->
    <div class="row mt-5 mb-2 justify-content-end">
        <div class="col-2 m-1">
            <a class="btn btn-primary" href="@Model?.ReturnUrl">Adicionar mais Cupcakes</a>
        </div>
        <div class="col-1 m-1">
            <a class="btn btn-primary" asp-action="Checkout" asp-controller="Produto">
                Finalizar compra
            </a>
        </div>
    </div>

Pages/ConclusaoPedido.cshtml
@page


<div class="text-center">
    <div class="figure-container">
        <img src="~/images/logo2.jpg" class="img-fluid image-opacity" alt="Logo da Loja" style="height: 120px;">
    </div>
    <h2 class="display-5">Cake-Lovers</h2>
</div>

<div class="text-center mt-5">
    <h1 class="mb-5">Obrigado pela Preferência!</h1>
    <h3 class="mb-2">O <strong class="text-danger">Pedido #@PedidoId</strong> está sendo processado com sucesso!</h3>
    <h3 class="mb-5">Logo será informado a situação da sua compra. Parabéns!!</h3>
    <a class="btn btn-primary" asp-controller="Home">Retornar às Compras</a>
</div>
@functions {
    [BindProperty(SupportsGet = true)]
    public string? PedidoId { get; set; }
}

Pages/_CartLayout.cshtml
@using com.cake_lovers.www.Intrastructure;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - Cake-lovers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/com.cake_lovers.www.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3 text-white">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">
                    <img src="~/images/logo2.jpg" alt="Logo da Loja" style="height: 35px;">
                    <span>Cake-lovers</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="justify-content-end">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="justify-content-end mx-4">
                            <a asp-page="/Cart" asp-route-Id="0" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()" class="cart-icon">
                                <i class="fas fa-shopping-cart text-white">
                                </i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>